// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lista_de_computadores.Data;

namespace lista_de_computadores.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("lista_de_computadores.Models.Computador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("hdEMarca")
                        .HasColumnType("TEXT");

                    b.Property<string>("imagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("marca")
                        .HasColumnType("TEXT");

                    b.Property<string>("modelo")
                        .HasColumnType("TEXT");

                    b.Property<string>("placa_mae")
                        .HasColumnType("TEXT");

                    b.Property<string>("ram")
                        .HasColumnType("TEXT");

                    b.Property<string>("velocidadeDoProcessador")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Computador");

                    b.HasData(
                        new
                        {
                            id = 2,
                            hdEMarca = "500gb SeaGate",
                            imagem = "generico",
                            marca = "Compaq",
                            modelo = "Compaq",
                            placa_mae = "3354288",
                            ram = "generico",
                            velocidadeDoProcessador = "generico"
                        },
                        new
                        {
                            id = 3,
                            hdEMarca = "generico",
                            imagem = "generico",
                            marca = "IBM",
                            modelo = "Antonia",
                            placa_mae = "55668899",
                            ram = "generico",
                            velocidadeDoProcessador = "generico"
                        },
                        new
                        {
                            id = 4,
                            hdEMarca = "generico",
                            imagem = "generico",
                            marca = "Dell",
                            modelo = "Maria",
                            placa_mae = "6565659",
                            ram = "generico",
                            velocidadeDoProcessador = "generico"
                        },
                        new
                        {
                            id = 5,
                            hdEMarca = "generico",
                            imagem = "generico",
                            marca = "SAMSUNG",
                            modelo = "Machado",
                            placa_mae = "565685415",
                            ram = "generico",
                            velocidadeDoProcessador = "generico"
                        },
                        new
                        {
                            id = 6,
                            hdEMarca = "generico",
                            imagem = "generico",
                            marca = "Toshiba",
                            modelo = "Alvares",
                            placa_mae = "456454545",
                            ram = "generico",
                            velocidadeDoProcessador = "generico"
                        },
                        new
                        {
                            id = 7,
                            hdEMarca = "generico",
                            imagem = "generico",
                            marca = "Positivo",
                            modelo = "José",
                            placa_mae = "9874512",
                            ram = "generico",
                            velocidadeDoProcessador = "generico"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
